language: java

# default install is mvn install --quiet -DskipTests=true
install: mvn --show-version --errors install
#invoker.streamLogs: we cannot access to log files through Travis web ui, so display everything in the console
script: mvn --show-version --errors clean install -Dinvoker.streamLogs=true
branches:
  only:
    - master
    - 0_5_X
 
env:
  global:
    - SONATYPE_USERNAME=chicchiricco
    - secure: "GeYWdEWPJDeXyVn29hUfwlbS0lp+O7hArW3Fzows3XpG9ZENGJKy9kK3pbHa\nenw2JrYtCXE47TNkmH6gHbq1yJGbgRFLYoTwiRWpAZ491veRlSs1s8qWBnir\nAoc7rPAK6f4I6Uhn20MFZXbvgKgx9/xCkQ2cP4hzshAaTt4tna0="

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { python .travis.addServer.py; mvn clean deploy --settings ~/.m2/mySettings.xml; };"

notifications:
  email:
    - hippococoontoolkit@googlegroups.com
